---
/content/urlrewriter/rules/site:
  hippo:name: Site
  hippostd:foldertype:
  - new-urlrewriter-folder
  - new-urlrewriter-document
  jcr:mixinTypes:
  - hippo:named
  - mix:referenceable
  jcr:primaryType: urlrewriter:ruleset
